apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devops-python"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/devops-python/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ "{{" }}- with secret "secret/data/devops-python/config" -{{ "}}" }}
          USERNAME={{ "{{" }} .Data.data.username {{ "}}" }}
          PASSWORD={{ "{{" }} .Data.data.password {{ "}}" }}
          APP_ENV=production
          {{ "{{" }}- end -{{ "}}" }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- include "devops-python.envVars" . | nindent 8 }}
        envFrom:
          - secretRef:
              name: {{ include "common.fullname" . }}-secret
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
