apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-python-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-python
      app.kubernetes.io/instance: devops-python
  endpoints:
    - targetPort: 8000
      path: /metrics
      interval: 15s
